### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by TimRepke** [TimRepke/registration-system#36]
Wir sollten in Zukunft einen Disclaimer haben!!!
Im Wiki ist eine Ideensammlung, was in den Disclaimer rein muss:
https://github.com/TimRepke/registration-system/wiki/%5BWIP%5D-Disclaimer

**TODO:**
- [ ] Ideen sammeln
- [ ] Formulierung ausfeilen
- [x] Disclaimer page anlegen
- [x] Disclaimer checkbox checked check einbauen
- [x] checkbox ins Formular einbauen (mit Link zu disclaimer)

**Comment by TimRepke** [comment]
Implementierung:
- Feld in die Fahrt Tabelle hinzufügen mit Disclaimer Version
- Via Admin/Infos Version setzbar machen
- Linkt auf eine spezifische Version im FS Wiki des Disclaimers
- Anmeldefrontend anpassen
- Rest siehe oben.

**Comment by TimRepke** [comment]
Ich denke, dieses Ticket kann geschlossen werden. Hat nichts mehr mit dem System zu tun, der Disclaimer ist im Fachschaftswiki und wird dort gepflegt (ausbaufährig...).
